// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITkYm5WTbmUCjl0_fy3uqJc2rCURoMLE',
    appId: '1:185105578159:web:670b7f8611b2cd08ddbc5a',
    messagingSenderId: '185105578159',
    projectId: 'study-flutter-08-cchef05-chat2',
    authDomain: 'study-flutter-08-cchef05-chat2.firebaseapp.com',
    storageBucket: 'study-flutter-08-cchef05-chat2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxHPWHo0oa9f7XorGT-X4HXsVc4zhn7I',
    appId: '1:185105578159:android:75eb504d6f6b38e7ddbc5a',
    messagingSenderId: '185105578159',
    projectId: 'study-flutter-08-cchef05-chat2',
    storageBucket: 'study-flutter-08-cchef05-chat2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYCg9Ra9Ip1TQPmSRv0o5-8W88wtE8Ws',
    appId: '1:185105578159:ios:b1bf64443a91cc3fddbc5a',
    messagingSenderId: '185105578159',
    projectId: 'study-flutter-08-cchef05-chat2',
    storageBucket: 'study-flutter-08-cchef05-chat2.appspot.com',
    iosClientId: '185105578159-p2p72c2ucakltv2t5p6edk103ien7k4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter08Codingchef05Chat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYCg9Ra9Ip1TQPmSRv0o5-8W88wtE8Ws',
    appId: '1:185105578159:ios:b1bf64443a91cc3fddbc5a',
    messagingSenderId: '185105578159',
    projectId: 'study-flutter-08-cchef05-chat2',
    storageBucket: 'study-flutter-08-cchef05-chat2.appspot.com',
    iosClientId: '185105578159-p2p72c2ucakltv2t5p6edk103ien7k4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter08Codingchef05Chat2',
  );
}
